services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password123
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=VendingMachine
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# For somehow it doesn't work
#  vending-machine-controller:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: vending-machine-controller
#    depends_on:
#      db:
#        condition: service_healthy
#    volumes:
#      - ./:/usr/src
#    command: python app.py
#    ports:
#      - "5000:5000"
#    environment:
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=password123
#      - MYSQL_ROOT_PASSWORD=password123
#      - MYSQL_DATABASE=db